project_id = "adama-eats"

[api]
enabled = true

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true

[auth.sms]
enable_signup = true
enable_confirmations = false

[storage]
enabled = true

[realtime]
enabled = true
