const image = (id, width = 900) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=82`

export const categories = [
  { id: 'all', label: 'All nearby', icon: '✦' },
  { id: 'traditional', label: 'Traditional', icon: '◉' },
  { id: 'breakfast', label: 'Breakfast', icon: '☀' },
  { id: 'fast-food', label: 'Fast food', icon: '⌁' },
  { id: 'drinks', label: 'Drinks & coffee', icon: '◒' },
  { id: 'desserts', label: 'Desserts', icon: '♡' },
]

export const restaurants = [
  {
    id: 'buna-kitchen',
    name: 'Buna Kitchen',
    cuisine: 'Ethiopian · Coffee',
    description: 'Slow-cooked favorites, fresh injera, and the coffee Adama wakes up for.',
    rating: 4.9,
    reviews: 186,
    eta: '20–30 min',
    deliveryFee: 60,
    distance: '1.2 km',
    badge: 'Most loved',
    image: image('photo-1517248135467-4c7edcad34c4'),
    logo: 'BK',
    logoClass: 'logo-buna',
    menu: [
      {
        id: 'buna-1',
        name: 'Buna ceremony coffee',
        description: 'Freshly roasted Ethiopian coffee with berbere butter.',
        price: 45,
        category: 'drinks',
        popular: true,
        image: image('photo-1495474472287-4d71bcdd2085', 500),
      },
      {
        id: 'buna-2',
        name: 'Doro tibs',
        description: 'Tender chicken, onion, niter kibbeh, and berbere sauce.',
        price: 420,
        category: 'traditional',
        popular: true,
        image: image('photo-1547592180-85f173990554', 500),
      },
      {
        id: 'buna-3',
        name: 'Shiro wat',
        description: 'Creamy chickpea stew served with warm injera.',
        price: 260,
        category: 'traditional',
        image: image('photo-1546069901-ba9599a7e63c', 500),
      },
      {
        id: 'buna-4',
        name: 'Kocho & ayib',
        description: 'Traditional fermented flatbread with mild cheese.',
        price: 180,
        category: 'breakfast',
        image: image('photo-1601050690597-df0568f70950', 500),
      },
    ],
  },
  {
    id: 'adama-grill',
    name: 'Adama Grill House',
    cuisine: 'Grill · Burgers',
    description: 'Juicy grilled favorites, crispy sides, and quick delivery.',
    rating: 4.7,
    reviews: 94,
    eta: '25–40 min',
    deliveryFee: 80,
    distance: '2.4 km',
    badge: 'Fast delivery',
    image: image('photo-1552566626-52f8b828add9'),
    logo: 'AG',
    logoClass: 'logo-grill',
    menu: [
      {
        id: 'grill-1',
        name: 'Adama beef burger',
        description: 'Smoked beef, cheddar, lettuce, tomato, and house sauce.',
        price: 295,
        category: 'fast-food',
        popular: true,
        image: image('photo-1568901346375-23c9450c58cd', 500),
      },
      {
        id: 'grill-2',
        name: 'Kitfo skewer',
        description: 'Minced beef with mitmita and grilled onion.',
        price: 360,
        category: 'traditional',
        image: image('photo-1529692236671-f46f6ad4b7ad', 500),
      },
      {
        id: 'grill-3',
        name: 'Crispy chicken bites',
        description: 'Golden chicken, house dip, and fresh salad.',
        price: 240,
        category: 'fast-food',
        image: image('photo-1562967914-608f82629710', 500),
      },
      {
        id: 'grill-4',
        name: 'House lemonade',
        description: 'Fresh lemon, mint, and a little sparkle.',
        price: 70,
        category: 'drinks',
        image: image('photo-1523677011781-c91d1bbe2f9d', 500),
      },
    ],
  },
  {
    id: 'selam-pizza',
    name: 'Selam Pizza Corner',
    cuisine: 'Pizza · Italian',
    description: 'Wood-fired pizza, creamy sides, and something for everyone.',
    rating: 4.6,
    reviews: 73,
    eta: '30–45 min',
    deliveryFee: 100,
    distance: '3.1 km',
    badge: 'New on Adama Eats',
    image: image('photo-1579751626657-72bc17010498'),
    logo: 'SP',
    logoClass: 'logo-pizza',
    menu: [
      {
        id: 'pizza-1',
        name: 'Selam special pizza',
        description: 'Tomato, mozzarella, beef, onion, and green pepper.',
        price: 390,
        category: 'fast-food',
        popular: true,
        image: image('photo-1574071318508-1cdbab80d002', 500),
      },
      {
        id: 'pizza-2',
        name: 'Margherita',
        description: 'San Marzano tomato, basil, and mozzarella.',
        price: 320,
        category: 'fast-food',
        image: image('photo-1579751626657-72bc17010498', 500),
      },
      {
        id: 'pizza-3',
        name: 'Garlic bread',
        description: 'Toasted sourdough with garlic butter and herbs.',
        price: 120,
        category: 'traditional',
        image: image('photo-1573140401552-3fab0b24306f', 500),
      },
      {
        id: 'pizza-4',
        name: 'Mint lemonade',
        description: 'House-made mint lemonade.',
        price: 75,
        category: 'drinks',
        image: image('photo-1497534446932-c925b458314e', 500),
      },
    ],
  },
  {
    id: 'mama-gebru',
    name: "Mama Gebru's Table",
    cuisine: 'Traditional · Vegan',
    description: 'Home-style fasting and family recipes made with heart.',
    rating: 4.8,
    reviews: 121,
    eta: '35–50 min',
    deliveryFee: 70,
    distance: '2.8 km',
    badge: 'Local favorite',
    image: image('photo-1515003197210-e0cd71810b5f'),
    logo: 'MG',
    logoClass: 'logo-mama',
    menu: [
      {
        id: 'mama-1',
        name: 'Misir wot',
        description: 'Spiced lentil stew with onion and garlic.',
        price: 220,
        category: 'traditional',
        popular: true,
        image: image('photo-1546069901-ba9599a7e63c', 500),
      },
      {
        id: 'mama-2',
        name: 'Fasting combo',
        description: 'Lentils, salad, injera, and crispy potatoes.',
        price: 310,
        category: 'traditional',
        image: image('photo-1512621776951-a57141f2eefd', 500),
      },
      {
        id: 'mama-3',
        name: 'Payeb',
        description: 'Green salad with berbere and fresh herbs.',
        price: 95,
        category: 'traditional',
        image: image('photo-1540420773420-3366772f4999', 500),
      },
      {
        id: 'mama-4',
        name: 'Ethiopian tea',
        description: 'Floral black tea with orange and cinnamon.',
        price: 35,
        category: 'drinks',
        image: image('photo-1544787219-7f47ccb76574', 500),
      },
    ],
  },
  {
    id: 'sunrise-bakery',
    name: 'Sunrise Bakery',
    cuisine: 'Breakfast · Bakery',
    description: 'Warm pastries, sandwiches, and coffee to start your day.',
    rating: 4.5,
    reviews: 58,
    eta: '15–25 min',
    deliveryFee: 50,
    distance: '0.8 km',
    badge: 'Good morning',
    image: image('photo-1509440159596-0249088772ff'),
    logo: 'SB',
    logoClass: 'logo-sunrise',
    menu: [
      {
        id: 'sunrise-1',
        name: 'Sambusa breakfast box',
        description: 'Two sambusa, egg, and a small cup of coffee.',
        price: 165,
        category: 'breakfast',
        popular: true,
        image: image('photo-1601050690597-df0568f70950', 500),
      },
      {
        id: 'sunrise-2',
        name: 'Chefsah sandwich',
        description: 'Fresh baked bread, egg, tomato, and house cheese.',
        price: 125,
        category: 'breakfast',
        image: image('photo-1528735602780-2552fd46c7af', 500),
      },
      {
        id: 'sunrise-3',
        name: 'Mandazi',
        description: 'Warm, spiced Ethiopian pastry.',
        price: 35,
        category: 'breakfast',
        image: image('photo-1626074353765-517a681e40be', 500),
      },
      {
        id: 'sunrise-4',
        name: 'Iced coffee',
        description: 'Cold brew with a touch of milk.',
        price: 65,
        category: 'drinks',
        image: image('photo-1461023058943-07fcbe16d735', 500),
      },
    ],
  },
]

export const dashboardOrders = [
  { id: 'AE-1048', customer: 'Mekdes Alemu', restaurant: 'Buna Kitchen', total: 485, status: 'Preparing', time: '2 min ago', tone: 'orange' },
  { id: 'AE-1047', customer: 'Yonas Bekele', restaurant: 'Adama Grill House', total: 375, status: 'Ready for pickup', time: '8 min ago', tone: 'green' },
  { id: 'AE-1046', customer: 'Hana Girma', restaurant: 'Selam Pizza Corner', total: 465, status: 'On the way', time: '12 min ago', tone: 'blue' },
  { id: 'AE-1045', customer: 'Abel Tadesse', restaurant: "Mama Gebru's Table", total: 310, status: 'Delivered', time: '24 min ago', tone: 'slate' },
]

export const availableDriverOrders = [
  {
    id: 'AE-1049',
    restaurant: 'Buna Kitchen',
    customer: 'Mekdes A.',
    pickup: 'Buna Kitchen · Piazza',
    dropoff: 'Tufa area, Adama',
    distance: '2.1 km',
    fee: 75,
    eta: '25 min',
    items: '2 items · Doro tibs, coffee',
  },
  {
    id: 'AE-1050',
    restaurant: 'Selam Pizza Corner',
    customer: 'Dawit K.',
    pickup: 'Selam Pizza Corner',
    dropoff: 'Ayofa area, Adama',
    distance: '3.4 km',
    fee: 100,
    eta: '35 min',
    items: '3 items · Family pizza, lemonade',
  },
  {
    id: 'AE-1051',
    restaurant: 'Mama Gebru’s Table',
    customer: 'Sara N.',
    pickup: 'Mama Gebru’s Table',
    dropoff: 'Woreda 03, Adama',
    distance: '1.8 km',
    fee: 65,
    eta: '20 min',
    items: '2 items · Fasting combo, salad',
  },
]

export const approvalRequests = [
  { id: 1, name: 'Abel Tadesse', type: 'Restaurant owner', detail: 'Sunrise Bakery', initials: 'AT', tone: 'sunrise' },
  { id: 2, name: 'Marta T.', type: 'Driver', detail: 'Motorbike · 2 years', initials: 'MT', tone: 'driver' },
  { id: 3, name: 'Hana Girma', type: 'Restaurant owner', detail: 'Mama Gebru’s Table', initials: 'HG', tone: 'mama' },
]

export const pastOrders = [
  { id: 'AE-1038', restaurant: 'Adama Grill House', date: 'Yesterday', total: 375, status: 'Delivered', items: 'Adama beef burger, lemonade' },
  { id: 'AE-1012', restaurant: 'Buna Kitchen', date: '12 Sep 2026', total: 485, status: 'Delivered', items: 'Doro tibs, buna coffee' },
]

export const ownerMenu = restaurants[0].menu

export function getRestaurant(id) {
  return restaurants.find((restaurant) => restaurant.id === id)
}

export function getAllFoodItems() {
  return restaurants.flatMap((restaurant) =>
    restaurant.menu.map((item) => ({ ...item, restaurantId: restaurant.id, restaurantName: restaurant.name, deliveryFee: restaurant.deliveryFee })),
  )
}
